version: '3'
services:
  assassins-db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - assassins-nw

  assassins-web:
    image: assassins
    restart: always
    ports:
      - 5000:5000
    command: sh -c 'cd /home/root/webserver; git clone https://github.com/wfrice/Assassins.git .; python3 main.py'
    links:
      - "assassins-db:database"
    networks:
      - assassins-nw

networks:
  assassins-nw: